# Project scaffolding

from pathlib import Path

def scaffold_project(repo: Path, template: str, name: str):
    if template == "py_lib":
        (repo / "src" / name.replace("-", "_")).mkdir(parents=True, exist_ok=True)
        (repo / "tests").mkdir(exist_ok=True)
        (repo / "src" / name.replace("-", "_") / "__init__.py").write_text("__version__='0.1.0'\\n")
        (repo / "pyproject.toml").write_text(f"""[project]
name = "{name}"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []
""")
        (repo / "README.md").write_text(f"# {name}\\n\\nGenerated by FERN 🌱\\n")
    else:
        raise ValueError(f"Unknown template: {template}")